name: Cache Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Prime cache
      - name: prime-cache-5dc3582
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/demo-cache
          key: cache-5dc3582

      # Step 3: Echo cache result
      - name: Echo cache hit/miss
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
            # create some files in the cache path to store next time
            mkdir -p ~/.cache/demo-cache
            echo "Hello, cache!" > ~/.cache/demo-cache/file.txt
          fi
